package Model.Entity;
// Generated 22.05.2015 17:35:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;


/**
 * Cat generated by hbm2java
 */
@Entity
@Table(name="cat")
public class Cat  implements java.io.Serializable {
    @Id
    @Column(name="cat_id")
    @GeneratedValue
     private Integer catId;
    @Column(name="cat_name")
     private String catName;
    @OneToMany(mappedBy = "cat")
     private Set<Prod> prods = new HashSet<Prod>(0);

    public Cat() {
    }

    public Cat(String catName, Set<Prod> prods) {
       this.catName = catName;
       this.prods = prods;
    }
   @Column(name="catId",nullable=false)
    public Integer getCatId() {
        return this.catId;
    }
    
    public void setCatId(Integer catId) {
        this.catId = catId;
    }
    @Column(name="catName", nullable=false)
    public String getCatName() {
        return this.catName;
    }
    
    public void setCatName(String catName) {
        this.catName = catName;
    }
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="categories")
    public Set<Prod> getProds() {
        return this.prods;
    }
    
    public void setProds(Set<Prod> prods) {
        this.prods = prods;
    }




}


