package Model.Entity;
// Generated 22.05.2015 17:35:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.*;
import java.io.Serializable;

/**
 * Prod generated by hbm2java
 */
@Entity
@Table(name="prod")

public class Prod  implements Serializable {
//public class Prod {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "prod_id")
    private Integer prodId;
    
    private Cat cat;  
    @Column(name = "cat_id")
    private Integer catId;
    @Column(name = "prod_name")
    private String prodName;
    @Column(name = "price")
    private BigDecimal price;
     
    public Prod() {}
    

    public Prod(Cat cat, String prodName, BigDecimal price) {
       this.cat = cat;
       this.prodName = prodName;
       this.price = price;
    }
    
    public Integer getProdId() {
        return this.prodId;
    }
    
    private void setProdId(Integer prodId) {
        this.prodId = prodId;
    }
    public Cat getCat() {   
        return this.cat;
    }
    public Integer getCatId() {
        return this.catId;
    }
    public Cat getCatName() {
        return this.cat;
    }
    private void setCat(Cat cat) {
        this.cat = cat;
    }
    public String getProdName() {
        return this.prodName;
    }
    
    public void setProdName(String prodName) {
        this.prodName = prodName;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    
}


