package home.work.dto;
// Generated 22.05.2015 17:35:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cat generated by hbm2java
 */
public class Cat  implements java.io.Serializable {


     private Integer catId;
     private String catName;
     private Set<Prod> prods = new HashSet<Prod>(0);

    public Cat() {
    }

    public Cat(String catName, Set<Prod> prods) {
       this.catName = catName;
       this.prods = prods;
    }
   
    public Integer getCatId() {
        return this.catId;
    }
    
    public void setCatId(Integer catId) {
        this.catId = catId;
    }
    public String getCatName() {
        return this.catName;
    }
    
    public void setCatName(String catName) {
        this.catName = catName;
    }
    public Set<Prod> getProds() {
        return this.prods;
    }
    
    public void setProds(Set<Prod> prods) {
        this.prods = prods;
    }




}


