package home.work.dto;
// Generated 22.05.2015 17:35:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.*;
import java.io.Serializable;

/**
 * Prod generated by hbm2java
 */
//@Entity

public class Prod  implements Serializable {
     private Integer prodId;
     private Cat cat;
     private String prodName;
     private BigDecimal price;
    
    
/*
    public Prod(Cat cat, String prodName, BigDecimal price) {
       this.cat = cat;
       this.prodName = prodName;
       this.price = price;
    }
     */
    //@Id
    //@GeneratedValue(strategy = GenerationType.AUTO)
    
    public Integer getProdId() {
        return this.prodId;
    }
    
    private void setProdId(Integer prodId) {
        this.prodId = prodId;
    }
    private Cat getCat() {
        return this.cat;
    }
    
    private void setCat(Cat cat) {
        this.cat = cat;
    }
    public String getProdName() {
        return this.prodName;
    }
    
    public void setProdName(String prodName) {
        this.prodName = prodName;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}


